### ISSUE TITLE
investigate performance of ReadsPipelineSpark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1657]
I'm running with a 35GB file (namesorted), 60 executors, 1 core each, 7 GB each, 277 reducers, and see unexpected issues
- [ ] GC times can go as 20% of execution time in stage2 (treeAggregate)
- [ ] task duration goes up to 6.7min (median 1.5 min) - this seems too long
- [ ] peak execution memory can go up to 263.9 GB (!) (median 988.8 MB)

this ticket is to track the analysis of those issues

my original run http://dataflow01.broadinstitute.org:18088/history/application_1458881872901_0078/stages/

**Comment by akiezun** [comment]
Current timings:
![image](https://cloud.githubusercontent.com/assets/1993519/14097676/ac45c0fc-f541-11e5-81b0-c69f08248705.png)

**Comment by akiezun** [comment]
observation - right in the middle of treeAggregate phase, everything stops and logs contain things like
```
16/03/29 12:41:54 INFO BlockManagerInfo: Added broadcast_4_piece129 in memory on dataflow04.broadinstitute.org:36110 (size: 4.0 MB, free: 2.6 GB)
16/03/29 12:41:54 INFO BlockManagerInfo: Added broadcast_4_piece52 in memory on dataflow03.broadinstitute.org:55401 (size: 4.0 MB, free: 2.7 GB)
16/03/29 12:41:54 INFO BlockManagerInfo: Added broadcast_4_piece62 in memory on dataflow03.broadinstitute.org:40364 (size: 4.0 MB, free: 2.7 GB)
```

so it's broadcasting stuff. But I dont know what - is it variants or is it the reference?

**Comment by akiezun** [comment]
More investigation - clicking "Thread Dump" in the Executors tab of the Spark GUI gives a hint as to what's happening when.

At the beginning, one of the dumps is like this
```
.....(many frames in spark)
org.broadinstitute.hellbender.engine.spark.BroadcastJoinReadsWithVariants.lambda$join$3d1c3858$1(BroadcastJoinReadsWithVariants.java:30)
org.broadinstitute.hellbender.engine.spark.BroadcastJoinReadsWithVariants$$Lambda$62/1939165975.call(Unknown Source)
org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1030)
org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1030)
scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
scala.collection.convert.Wrappers$IteratorWrapper.next(Wrappers.scala:30)
org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$apply$26a6df3e$1(BaseRecalibratorSparkFn.java:28)
org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn$$Lambda$65/1280150357.call(Unknown Source)
```

then there are dumps like this
```
org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.lambda$markPairedEnds$66146993$1(MarkDuplicatesSparkUtils.java:182)
org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils$$Lambda$51/84990817.call(Unknown Source)
org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:126)
org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:126)
scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:29)
org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$apply$26a6df3e$1(BaseRecalibratorSparkFn.java:27)
org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn$$Lambda$65/1110390847.call(Unknown Source)
```

and 
```
org.broadinstitute.hellbender.engine.filters.ReadFilter.lambda$and$cbfb947b$1(ReadFilter.java:31)
org.broadinstitute.hellbender.engine.filters.ReadFilter$$Lambda$33/1797796358.test(Unknown Source)
org.broadinstitute.hellbender.engine.filters.ReadFilter.lambda$and$cbfb947b$1(ReadFilter.java:31)
org.broadinstitute.hellbender.engine.filters.ReadFilter$$Lambda$33/1797796358.test(Unknown Source)
org.broadinstitute.hellbender.engine.filters.ReadFilter.lambda$and$cbfb947b$1(ReadFilter.java:31)
org.broadinstitute.hellbender.engine.filters.ReadFilter$$Lambda$33/1797796358.test(Unknown Source)
org.broadinstitute.hellbender.engine.filters.ReadFilter.lambda$and$cbfb947b$1(ReadFilter.java:31)
org.broadinstitute.hellbender.engine.filters.ReadFilter$$Lambda$33/1797796358.test(Unknown Source)
org.broadinstitute.hellbender.engine.filters.WellformedReadFilter.test(WellformedReadFilter.java:31)
org.broadinstitute.hellbender.engine.spark.GATKSparkTool.lambda$getReads$e4b35a40$1(GATKSparkTool.java:196)
org.broadinstitute.hellbender.engine.spark.GATKSparkTool$$Lambda$39/818029262.call(Unknown Source)
org.apache.spark.api.java.JavaRDD$$anonfun$filter$1.apply(JavaRDD.scala:78)
org.apache.spark.api.java.JavaRDD$$anonfun$filter$1.apply(JavaRDD.scala:78)
scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:390)
scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:29)
org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$apply$26a6df3e$1(BaseRecalibratorSparkFn.java:27)
```

**Comment by akiezun** [comment]
I ran with -Xprof sent to executors and here's an example profile for the worker thread
```
Flat profile of 1238.95 secs (113045 total ticks): Executor task launch worker-0

  Interpreted + native   Method                        
  0.2%     0  +   153    java.net.Inet6AddressImpl.lookupAllHostAddr
  0.1%    56  +     0    org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSparkUtils.lambda$markPairedEnds$66146993$1
  0.1%     0  +    46    java.util.zip.Deflater.deflateBytes
  0.1%    46  +     0    org.broadinstitute.hellbender.tools.spark.transforms.BaseRecalibratorSparkFn.lambda$apply$26a6df3e$1
  0.1%    42  +     0    org.broadinstitute.hellbender.utils.baq.BAQ.hmm_glocal
  0.0%     0  +    28    java.net.SocketInputStream.socketRead0
  0.0%    22  +     0    org.apache.spark.util.collection.TimSort.sort
  0.0%    15  +     0    java.util.Iterator.forEachRemaining
  0.0%    14  +     0    org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp
  0.0%    13  +     0    com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read
  0.0%     6  +     0    org.broadinstitute.hellbender.utils.baq.BAQ.<init>
  0.0%     4  +     0    org.broadinstitute.hellbender.utils.recalibration.RecalUtils.combineTables
  0.0%     0  +     3    java.io.UnixFileSystem.getLength
  0.0%     3  +     0    org.apache.hadoop.hdfs.DFSOutputStream.waitAndQueueCurrentPacket
  0.0%     3  +     0    org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.processRead
  0.0%     0  +     2    java.io.UnixFileSystem.createDirectory
  0.0%     1  +     1    java.lang.Class.getDeclaredFields0
  0.0%     2  +     0    java.nio.HeapIntBuffer.<init>
  0.0%     2  +     0    sun.misc.Unsafe.defineClass
  0.0%     0  +     2    sun.misc.Unsafe.copyMemory
  0.0%     0  +     2    org.apache.hadoop.util.NativeCrc32.nativeComputeChunkedSums
  0.0%     2  +     0    java.text.DateFormatSymbols.getProviderInstance
  0.0%     2  +     0    org.broadinstitute.hellbender.utils.baq.BAQ$BAQCalculationResult.<init>
  0.0%     2  +     0    org.broadinstitute.hellbender.utils.read.markduplicates.ReadsKey.subkeyForFragment
  0.0%     2  +     0    htsjdk.samtools.BAMRecord.decodeBaseQualities
  0.8%   396  +   260    Total interpreted (including elided)

     Compiled + native   Method                        
 13.4% 10629  +    23    org.bdgenomics.adam.util.TwoBitFile$$anonfun$2.apply$mcZJ$sp
  8.6%    21  +  6794    org.broadinstitute.hellbender.utils.baq.BAQ.hmm_glocal
  5.7%  4492  +     0    org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.updateRecalTablesForRead
  4.1%  3246  +     0    scala.collection.AbstractTraversable.genericBuilder
  2.4%  1932  +     0    scala.collection.AbstractSeq.size
  2.3%  1841  +     2    com.ning.compress.lzf.impl.UnsafeChunkEncoderLE.tryCompress
  2.0%  1560  +     0    org.broadinstitute.hellbender.transformers.BQSRReadTransformer.apply
  1.8%  1407  +     0    org.broadinstitute.hellbender.utils.collections.IntervalsSkipListOneContig.getOverlapping
  1.3%  1034  +     0    scala.collection.mutable.ArrayBuilder.sizeHint
  1.1%   898  +     0    com.ning.compress.lzf.impl.UnsafeChunkDecoder.decodeChunk
  1.1%   893  +     4    scala.collection.mutable.ArrayBuilder$.make
  1.1%   881  +     2    org.broadinstitute.hellbender.utils.recalibration.BaseRecalibrationEngine.processRead
  1.0%   758  +     0    org.broadinstitute.hellbender.utils.recalibration.RecalUtils.computeCovariates
  0.9%   698  +     0    htsjdk.samtools.BinaryTagCodec.readTags
  0.7%   573  +     0    htsjdk.samtools.util.BlockCompressedOutputStream.write
  0.7%   535  +     0    org.broadinstitute.hellbender.utils.recalibration.covariates.ContextCovariate.recordValues
  0.6%   506  +     1    htsjdk.samtools.BinaryTagCodec.readSingleValue
  0.6%   459  +     1    scala.collection.Iterator$$anon$13.hasNext
  0.5%   400  +     0    org.broadinstitute.hellbender.relocated.com.google.common.collect.AbstractMapBasedMultimap.put
  0.5%   370  +     1    org.broadinstitute.hellbender.utils.baq.BAQ.calcBAQFromHMM
  0.5%   360  +     0    org.broadinstitute.hellbender.relocated.com.google.common.collect.ImmutableListMultimap.copyOf
  0.4%   348  +     5    scala.collection.IndexedSeqOptimized$class.zip
  0.4%   330  +     3    com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read
  0.4%   325  +     0    htsjdk.samtools.SAMBinaryTagAndValue.find
  0.4%   322  +     0    org.broadinstitute.hellbender.utils.read.SAMRecordToGATKReadAdapter.getReadGroup
 66.2% 45378  +  7026    Total compiled (including elided)

         Stub + native   Method                        
 11.8%     0  +  9359    java.lang.String.intern
  7.1%     0  +  5608    java.util.zip.Deflater.deflateBytes
  6.9%     0  +  5492    java.lang.System.identityHashCode
  2.8%     0  +  2196    java.util.zip.Inflater.inflateBytes
  1.8%     0  +  1447    java.net.SocketInputStream.socketRead0
  0.6%     0  +   484    java.io.FileOutputStream.writeBytes
  0.4%     0  +   285    java.util.zip.Inflater.reset
  0.3%     0  +   259    sun.nio.ch.NativeThread.current
  0.3%     0  +   222    sun.nio.ch.EPollArrayWrapper.epollWait
  0.2%     0  +   137    java.util.zip.Deflater.reset
  0.1%     0  +   115    sun.nio.ch.FileDispatcherImpl.read0
  0.1%     0  +   113    org.apache.hadoop.util.NativeCrc32.nativeComputeChunkedSumsByteArray
  0.1%    67  +     4    java.lang.ClassLoader.defineClass1
  0.1%     0  +    51    java.util.zip.ZipFile.getEntry
  0.1%     0  +    41    java.lang.Throwable.fillInStackTrace
  0.0%     0  +    24    org.apache.hadoop.util.NativeCrc32.nativeComputeChunkedSums
  0.0%     0  +    23    java.lang.System.arraycopy
  0.0%     0  +    18    java.lang.Object.clone
  0.0%     1  +    15    java.io.UnixFileSystem.getBooleanAttributes0
  0.0%     0  +    14    sun.reflect.Reflection.getClassAccessFlags
  0.0%     0  +    13    java.lang.Thread.isInterrupted
  0.0%     0  +    11    java.lang.Class.isPrimitive
  0.0%     0  +    11    java.lang.Class.isArray
  0.0%     0  +    10    sun.nio.ch.FileDispatcherImpl.size0
  0.0%     4  +     5    java.security.AccessController.doPrivileged
 33.0%    77  + 26077    Total stub (including elided)

  Thread-local ticks:
 29.9% 33828             Blocked (of total)
  0.0%     3             Class loader

```

**Comment by akiezun** [comment]
We need to figure out who's doing the String interning `11.8%     0  +  9359    java.lang.String.intern` ? Is it htsjdk?

**Comment by droazen** [comment]
@akiezun The `SAMRecord` class in htsjdk uses interning -- I bet that's it. We can try to remove it, but there could be side effects (eg., client code might be relying on `==` equality for contig names).

**Comment by akiezun** [comment]
I need to profile this - does intern() save enough heap that the speed
penalty is justified?

If someone is relying on `==` for string comparing they are insane, I don't
think the API mentions that.

**Comment by droazen** [comment]
@akiezun Nevertheless, I have absolutely seen htsjdk client code that relies on interning and `==` on Strings. Which is silly, since the first thing `String.equals()` does is:

        if (this == anObject) {
            return true;
        }

**Comment by akiezun** [comment]
I did a quick sanity check in htsjdk PrintReadsExample with and without intern() in SAMRecord and SAMSequenceRecord and see no difference on bam of 12GB. So this excessive intern() time is either Spark-specific or not htsjdk-related.

**Comment by cmnbroad** [comment]
The Spark code resets the record headers using setHeaderStrict, which always resolves reference names and indices, which in turn can result in interning. An easy one-line change to test that hypothesis would be to change htsjdk SAMRecord.setHeaderStrict to just forward to setHeader and compare the results.

**Comment by akiezun** [comment]
cool. but will hadoop-bam pick up my homemade htsjdk jar?

**Comment by cmnbroad** [comment]
No (although you can build and integrate that locally as well - I do that quite a bit), but Hadoop-BAM doesn't use setHeaderStrict (yet!) so I don't think its necessary for this test. The calls I suspect are in GATK code.

**Comment by cmnbroad** [comment]
Actually, I think Hadoop-BAM *will* pick up the local htsjdk, since I've had problems in the past due to the fact that  Hadoop-BAM is built with an older version of htsjdk than GATK is, but it runs with the (usually newer) version provided by GATK. But either way for this test it shouldn't matter.

**Comment by akiezun** [comment]
here's one stacktrace for intern:
```
java.lang.String.intern(Native Method)
htsjdk.samtools.SAMRecord.setReferenceName(SAMRecord.java:367)
org.broadinstitute.hellbender.engine.spark.SAMRecordToGATKReadAdapterSerializer.read(SAMRecordToGATKReadAdapterSerializer.java:46)
org.broadinstitute.hellbender.engine.spark.SAMRecordToGATKReadAdapterSerializer.read(SAMRecordToGATKReadAdapterSerializer.java:14)
```

**Comment by akiezun** [comment]
meh, removing interning does not change any runtimes: I tried it on MarkDuplicatesSpark.

**Comment by akiezun** [comment]
This ticket is too broad. Replacing with:
https://github.com/broadinstitute/gatk/issues/1809
https://github.com/broadinstitute/gatk/issues/1675
https://github.com/broadinstitute/gatk/issues/1807
https://github.com/broadinstitute/gatk/issues/1810
https://github.com/broadinstitute/gatk/issues/1811

**Comment by akiezun** [comment]
reopening as epic

**Comment by Blaok** [comment]
We encountered similar issue and we solved it with this commit in adam-core: https://github.com/bigdatagenomics/adam/pull/1426 . Maybe you would want to have a look at it.

**Comment by droazen** [comment]
Closing -- this epic is complete.
