### ISSUE TITLE
CNN checklist for pre-AGBT release

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#4225]
Before Sam's awesome AGBT talk extolling the virtues of the new GATK-CNN filtering tool we want to be able to make a GATK release with the following:
[ ] A cool name!
[ ] Model training script (in Python, eventually in Java)
[ ] Pretrained model for WGS
[ ] Pretrained model for WEx
[ ] Model inference and VCF annotation (in Java)
[ ] Solution for applying filters based on CNN score cutoff
[ ] Alternate joint calling WDL?  Or for re-filtering? (ideally with a $$$ estimate)
[ ] Performance optimizations?

**Comment by lucidtronix** [comment]
Update:
- [ ] A cool name! (Marduk, Clarendon, NeuroVar) ? maybe I'll do a slack poll of dsde methods?
- [x] Model training script (in Python, eventually in Java)
- [x] Pretrained model for WGS
- [x] Pretrained model for WEx (still being validated and was only trained on NA12878)
- [x] Model inference and VCF annotation (in Java)
- [x] Solution for applying filters based on CNN score cutoff (tranches.py script)
- [ ] Alternate joint calling WDL? Or for re-filtering? (ideally with a $$$ estimate)
- [ ] Performance optimizations?

**Comment by ldgauthier** [comment]
My calculations give a runtime estimate of $0.18 for the 1D and... more for the 2D.  We'll optimize later.  It'll be fine.

**Comment by lucidtronix** [comment]
Finished, [2D CNN inference](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/vqsr/CNNScoreVariants.java) and training merged, many new issues spawned.:
- [X] A cool(?) name CNNScoreVariants
- [x] Model training script (in Python, eventually in Java)
- [x] Pretrained model for WGS
- [x] Pretrained model for WEx (still being validated and was only trained on NA12878)
- [x] Model inference and VCF annotation (in Java)
- [x] Solution for applying filters based on CNN score cutoff (tranches.py script)
- [x] Currently just re-filtering. Still no joint calling solution...
- [x] Hyperparameters optimized for small 2d model similar performance but .25 params.
